### ISSUE TITLE
Jibri recording and live streaming starts and stops.

### ISSUE THREAD

**Issue by vinodkrish2004** [jitsi/jibri#143]
Hi

 I was testing Jitsi Meet created on a EC2 instance on AWS. I am impressed with its features and works  fine. Recently I added Jibri instance for recording and streaming, I could initiate the recording from the interface but it stops automatically. It is creating folders on Jibri but no file in it... below is the info i get from root...

root@ip-172-31-27-193:~# ls /srv/recordings/
fqrkjgxudbkymypc  spwuchufgqyeqtsc  uhjiawoduwxyaezb
roqdlvvunrmejusu  tlxwgcqbhofxrqsa
root@ip-172-31-27-193:~# ls /srv/recordings/fqrkjgxudbkymypc
metadata.json
root@ip-172-31-27-193:~#

What could be the reason? Any suggestions..

**Comment by bbaldino** [comment]
Include Jibri logs please.

**Comment by vinodkrish2004** [comment]
created Jibri on a large instance now but  have lost access to recording tab...
 jicofo seems to discover the recorder but still the reocrder tab is disabled...

**Comment by vinodkrish2004** [comment]
Jicofo 2018-08-19 02:55:20.823 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member squarealiensmergehappily@conference.rozbolee.com/a1267838 is leaving
Jicofo 2018-08-19 02:55:20.823 WARNING: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Participant not found for squarealiensmergehappily@conference.rozbolee.com/a1267838 terminated already or never started ?
Jicofo 2018-08-19 02:55:20.830 INFO: [37] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: squarealiensmergehappily@conference.rozbolee.com conference count: 0
Jicofo 2018-08-19 02:58:12.373 INFO: [41] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: jealouscowsemancipateexactly@conference.rozbolee.com
Jicofo 2018-08-19 02:58:12.373 INFO: [41] org.jitsi.jicofo.FocusManager.log() Created new focus for jealouscowsemancipateexactly@conference.rozbolee.com@auth.rozbolee.com conferences count: 1 options:
    channelLastN: -1
    enableLipSync: true
    openSctp: true
    disableRtx: false
Jicofo 2018-08-19 02:58:12.373 INFO: [41] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Lip-sync enabled in jealouscowsemancipateexactly@conference.rozbolee.com
Jicofo 2018-08-19 02:58:12.373 INFO: [41] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Joining the room: jealouscowsemancipateexactly@conference.rozbolee.com
Jicofo 2018-08-19 02:58:12.442 INFO: [37] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@6c2167c6 member=ChatMember[jealouscowsemancipateexactly@conference.rozbolee.com/2ddbc6d9, jid: null]@308994285]
Jicofo 2018-08-19 02:58:12.444 INFO: [37] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to jealouscowsemancipateexactly@conference.rozbolee.com/2ddbc6d9
Jicofo 2018-08-19 02:58:12.445 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member jealouscowsemancipateexactly@conference.rozbolee.com/2ddbc6d9 joined.
Jicofo 2018-08-19 02:58:20.475 INFO: [37] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@6c2167c6 member=ChatMember[jealouscowsemancipateexactly@conference.rozbolee.com/2ddbc6d9, jid: 2ddbc6d9-6505-49c0-bcb3-3c094130212e@rozbolee.com/b9be035c-8f50-4bf0-9eac-2260439bb742]@308994285]
Jicofo 2018-08-19 02:58:20.475 INFO: [37] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Owner has left the room !
Jicofo 2018-08-19 02:58:20.476 INFO: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member jealouscowsemancipateexactly@conference.rozbolee.com/2ddbc6d9 is leaving
Jicofo 2018-08-19 02:58:20.476 WARNING: [37] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Participant not found for jealouscowsemancipateexactly@conference.rozbolee.com/2ddbc6d9 terminated already or never started ?
Jicofo 2018-08-19 02:58:20.477 INFO: [37] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: jealouscowsemancipateexactly@conference.rozbolee.com conference count: 0

**Comment by vinodkrish2004** [comment]
2018-08-18 18:59:45.900 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
2018-08-18 18:59:46.458 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed config:
JibriConfig(recordingDirectory=/srv/recordings, enabledStatsD=true, finalizeRecordingScriptPath=/path/to/finalize_recording.sh, xmppEnvironments=[XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[rozbolee.com], xmppDomain=rozbolee.com, controlLogin=XmppCredentials(domain=auth.rozbolee.com, username=jibri, password=jibriauthpass), controlMuc=XmppMuc(domain=internal.auth.rozbolee.com, roomName=JibriBrewery, nickname=jibri-nickname), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.xmpp.rozbolee.com, username=recorder, password=jibrirecorderpass), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)])
2018-08-18 18:59:46.908 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored. 
2018-08-18 18:59:47.136 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on rozbolee.com with config XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[rozbolee.com], xmppDomain=rozbolee.com, controlLogin=XmppCredentials(domain=auth.rozbolee.com, username=jibri, password=jibriauthpass), controlMuc=XmppMuc(domain=internal.auth.rozbolee.com, roomName=JibriBrewery, nickname=jibri-nickname), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.xmpp.rozbolee.com, username=recorder, password=jibrirecorderpass), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)
2018-08-18 18:59:47.143 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2018-08-18 18:59:47.319 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.connected() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: connected
2018-08-18 18:59:47.380 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.authenticated() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: authenticated (resume from previous? false)
2018-08-18 18:59:47.428 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored. 
2018-08-18 19:09:19.841 WARNING: [25] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[jibri@auth.rozbolee.com/4dcb8471-417b-42e4-a225-def8e5668c88] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1048)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:982)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:998)
	at java.lang.Thread.run(Thread.java:748)
2018-08-18 19:09:19.842 INFO: [25] class org.jitsi.xmpp.mucclient.MucClient.connectionClosedOnError() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: closed on error: org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
2018-08-18 19:09:20.843 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 1
2018-08-18 19:09:21.843 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:21.844 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:21.847 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectionFailed() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnection failed: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'rozbolee.com:5222' failed because: rozbolee.com/172.31.26.150 exception: java.net.ConnectException: Connection refused (Connection refused)
2018-08-18 19:09:22.848 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 1
2018-08-18 19:09:23.848 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:23.849 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:53.879 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectionFailed() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnection failed: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'rozbolee.com:5222' failed because: rozbolee.com/172.31.26.150 exception: java.net.SocketTimeoutException: connect timed out
2018-08-18 19:09:54.880 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 1
2018-08-18 19:09:55.881 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:55.881 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:55.882 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectionFailed() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnection failed: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'rozbolee.com:5222' failed because: rozbolee.com/172.31.26.150 exception: java.net.ConnectException: Connection refused (Connection refused)
2018-08-18 19:09:56.883 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 1
2018-08-18 19:09:57.883 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:57.884 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:57.885 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectionFailed() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnection failed: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'rozbolee.com:5222' failed because: rozbolee.com/172.31.26.150 exception: java.net.ConnectException: Connection refused (Connection refused)
2018-08-18 19:09:58.885 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 1
2018-08-18 19:09:59.886 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:59.886 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.reconnectingIn() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: reconnecting in 0
2018-08-18 19:09:59.957 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.connected() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: connected
2018-08-18 19:10:00.022 INFO: [41] class org.jitsi.xmpp.mucclient.MucClient.authenticated() [prod environment: auth.rozbolee.com@rozbolee.com] Xmpp connection status: authenticated (resume from previous? false)
2018-08-18 19:16:42.808 INFO: [27] org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq() Received JibriIq <iq to='jibri@auth.rozbolee.com/77b40ba9-247f-4acd-9b9a-153e8ecec808' from='jibribrewery@internal.auth.rozbolee.com/focus' id='amlicmlAYXV0aC5yb3pib2xlZS5jb20vNzdiNDBiYTktMjQ3Zi00YWNkLTliOWEtMTUzZThlY2VjODA4AEczSERkLTQwNQAIuxXO9/d3ltB0Y4uQ8TpO' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='stream' room='creepysiblingsfeedcasually@conference.rozbolee.com' streamid='k9p9-k28w-k7zf-d3as' session_id='mfjnexcpjxpmatql'/></iq> from environment prod environment
2018-08-18 19:16:42.810 INFO: [27] org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq() Received start request
2018-08-18 19:16:42.811 INFO: [27] org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq() Sending 'pending' response to start IQ
2018-08-18 19:16:42.811 INFO: [47] org.jitsi.jibri.api.xmpp.XmppApi.run() Starting service
2018-08-18 19:16:42.815 INFO: [47] org.jitsi.jibri.api.xmpp.XmppApi.handleStartService() Parsed call url info: CallUrlInfo(baseUrl=https://rozbolee.com, callName=creepysiblingsfeedcasually, urlParams=[])
2018-08-18 19:16:42.816 INFO: [47] org.jitsi.jibri.JibriManager.startStreaming() Starting a stream with params: ServiceParams(usageTimeoutMinutes=0) StreamingParams(callParams=CallParams(callUrlInfo=CallUrlInfo(baseUrl=https://rozbolee.com, callName=creepysiblingsfeedcasually, urlParams=[])), sessionId=mfjnexcpjxpmatql, callLoginParams=XmppCredentials(domain=recorder.xmpp.rozbolee.com, username=recorder, password=jibrirecorderpass), youTubeStreamKey=k9p9-k28w-k7zf-d3as, youTubeBroadcastId=null)
2018-08-18 19:16:42.820 FINE: [47] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.<init>() Detected os as OS: LINUX
2018-08-18 19:16:43.596 INFO: [47] org.openqa.selenium.remote.ProtocolHandshake.createSession() Detected dialect: OSS
2018-08-18 19:16:43.607 FINE: [47] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: start:live_stream
2018-08-18 19:16:43.607 INFO: [47] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now busy, publishing presence to connection prod environment
2018-08-18 19:16:44.643 FINE: [47] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Visiting url https://rozbolee.com/creepysiblingsfeedcasually#config.iAmRecorder=true&config.externalConnectUrl=null&config.startWithAudioMuted=true&config.startWithVideoMuted=true&interfaceConfig.APP_NAME="Jibri"
2018-08-18 19:17:16.694 SEVERE: [47] org.jitsi.jibri.selenium.pageobjects.CallPage.visit() Timed out waiting for call page to load
2018-08-18 19:17:16.695 SEVERE: [47] org.jitsi.jibri.service.impl.StreamingJibriService.start() Selenium failed to join the call
2018-08-18 19:17:16.695 FINE: [47] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:live_stream
2018-08-18 19:17:16.696 INFO: [47] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2018-08-18 19:17:16.696 INFO: [47] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Stopping capturer
2018-08-18 19:17:16.696 INFO: [47] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Stopping ffmpeg process
2018-08-18 19:17:16.696 INFO: [47] org.jitsi.jibri.capture.ffmpeg.executor.FfmpegExecutor.stopFfmpeg() Ffmpeg exited with value null
2018-08-18 19:17:16.696 INFO: [47] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Stopped capturer
2018-08-18 19:17:16.697 INFO: [47] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Quitting selenium
2018-08-18 19:17:16.707 INFO: [47] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 12 log entries for type browser
2018-08-18 19:17:16.809 INFO: [47] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 1011 log entries for type driver
2018-08-18 19:17:16.902 INFO: [47] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Got 0 log entries for type client
2018-08-18 19:17:16.903 INFO: [47] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Leaving web call
2018-08-18 19:17:16.910 INFO: [47] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Quitting chrome driver
2018-08-18 19:17:16.979 INFO: [47] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Chrome driver quit
2018-08-18 19:17:16.979 INFO: [47] org.jitsi.jibri.service.impl.StreamingJibriService.stop() Quit selenium
2018-08-18 19:17:16.980 INFO: [47] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now idle, publishing presence to connection prod environment
2018-08-18 19:17:16.980 FINE: [47] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: error:live_stream
2018-08-18 19:17:16.981 INFO: [47] org.jitsi.jibri.api.xmpp.XmppApi.run() Sending start service response iq: <iq to='jibribrewery@internal.auth.rozbolee.com/focus' id='38GCc-106' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error'/></iq>
2018-08-18 19:17:52.072 INFO: [19] org.jitsi.jibri.api.http.internal.InternalHttpApi.gracefulShutdown() Jibri gracefully shutting down

**Comment by Ark74** [comment]
Seems this is a recurring issue. :sob:

**Comment by Ark74** [comment]
The fix for Jibri was released.
Another requirement is to enable Dropbox app in order to record.
See more [here](https://github.com/jitsi/jitsi-meet/issues/3355).
