### ISSUE TITLE
Jibri start and joined Prosody but Jicofo can't find an available Jibri

### ISSUE THREAD

**Issue by mcarli** [jitsi/jibri#257]
Hi,
i've installed Jitsi and Jibri with debian package and followed the guide in readme, but the Jibri istance can connect to Prosody but Jicofo can't find it when a user request to record a meeting.

I have read many reports similar to this, but most had connection problems or dns resolution problem from jibri to prosody. In this case, it seems to me all right from this point of view.

My Jibri status:
`● jibri.service - Jibri Process
   Loaded: loaded (/etc/systemd/system/jibri.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-03-28 01:50:26 CET; 8h ago
  Process: 1535 ExecStop=/opt/jitsi/jibri/graceful_shutdown.sh (code=exited, status=0/SUCCESS)
 Main PID: 1544 (java)
    Tasks: 36
   Memory: 161.9M
      CPU: 18.505s
   CGroup: /system.slice/jibri.service
           └─1544 java -Djava.util.logging.config.file=/etc/jitsi/jibri/logging.properties -jar /opt/jitsi/jibri/jibri.jar --config /etc/jitsi/jibri/config.json

Mar 28 01:50:26 fi-jibri systemd[1]: jibri.service: Main process exited, code=exited, status=143/n/a
Mar 28 01:50:26 fi-jibri systemd[1]: Stopped Jibri Process.
Mar 28 01:50:26 fi-jibri systemd[1]: jibri.service: Unit entered failed state.
Mar 28 01:50:26 fi-jibri systemd[1]: jibri.service: Failed with result 'exit-code'.
Mar 28 01:50:26 fi-jibri systemd[1]: Started Jibri Process.
Mar 28 01:50:27 fi-jibri launch.sh[1544]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
Mar 28 01:50:27 fi-jibri launch.sh[1544]: SLF4J: Defaulting to no-operation (NOP) logger implementation
Mar 28 01:50:27 fi-jibri launch.sh[1544]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
`

Follow my log and config file:
[sip-communicator.properties (Jicofo)](https://github.com/jitsi/jibri/files/4396896/sip-communicator.properties.jicofo.txt)
[config (Jicofo)](https://github.com/jitsi/jibri/files/4396897/config.jicofo.txt)
[config.json (Jibri)](https://github.com/jitsi/jibri/files/4396898/config.json.jibri.txt)
[jibri log](https://github.com/jitsi/jibri/files/4396899/jibri.txt)
[jicofo log](https://github.com/jitsi/jibri/files/4396900/jicofo.txt)
[jvb log](https://github.com/jitsi/jibri/files/4396901/jvb.txt)
[prosody.err](https://github.com/jitsi/jibri/files/4396902/prosody.err.txt)
[prosody.log](https://github.com/jitsi/jibri/files/4396903/prosody.log.txt)

**Comment by akalana** [comment]
Hi,
This issue occurred when I started to record, after connecting jibri.

**Comment by mcarli** [comment]
Yes, from Jibri log it seems all working correctly but, when i try to record a conference, from Web UI, Jitisi Meet report "Recording error" and Jicofo log that any Jibri is available

**Comment by akalana** [comment]
@mcarli In my situation when I click the recording button there is no action occurred in Jicofo log.

**Comment by mcarli** [comment]
My Jitsi machine is behind NAT (i'm using correctly org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS and
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS options)

Is it possible that the problem may have stemmed from the fact that Jibri contacts Jicofo on the LAN interface and not on the public interface where Jitsi is advertised?

**Comment by mcarli** [comment]
Found problem:

there is a typo into in /etc/jitsi/jicofo/sip-communicator.properties, so check org.jitsi.jicofo.jibri.BREWERY 

I found that because in jicofo.log i found this:
`Jicofo 2020-04-04 13:27:52.953 SEVERE: [17] org.jitsi.jicofo.xmpp.BaseBrewery.start().190 Failed to create room: JibriBrewery@**internal.auth.mydomain.com**
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to join the room
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.joinAs(ChatRoomImpl.java:298)
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.join(ChatRoomImpl.java:209)
        at org.jitsi.jicofo.xmpp.BaseBrewery.start(BaseBrewery.java:184)
        at org.jitsi.jicofo.xmpp.BaseBrewery.maybeStart(BaseBrewery.java:135)
        at org.jitsi.jicofo.xmpp.BaseBrewery.registrationStateChanged(BaseBrewery.java:160)
        at org.jitsi.jicofo.ProtocolProviderHandler.registrationStateChanged(ProtocolProviderHandler.java:141)
        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.notifyConnected(XmppProtocolProvider.java:335)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:62)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$XmppConnectionListener.authenticated(XmppProtocolProvider.java:623)
        at org.jivesoftware.smack.AbstractXMPPConnection.callConnectionAuthenticatedListener(AbstractXMPPConnection.java:1297)
        at org.jivesoftware.smack.AbstractXMPPConnection.afterSuccessfulLogin(AbstractXMPPConnection.java:572)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.afterSuccessfulLogin(XMPPTCPConnection.java:379)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginInternal(XMPPTCPConnection.java:444)
        at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:491)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:287)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from **internal.auth.mydomain.com: XMPPError: remote-server-not-found** - cancel
        at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:132)
        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:263)
        at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:214)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:540)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:506)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeatures(ServiceDiscoveryManager.java:748)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeatures(ServiceDiscoveryManager.java:744)
        at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeature(ServiceDiscoveryManager.java:740)
        at org.jivesoftware.smackx.muc.MultiUserChatManager.providesMucService(MultiUserChatManager.java:361)
        at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:311)
        at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:498)
        at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:444)
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.joinAs(ChatRoomImpl.java:240)`
