### ISSUE TITLE
Unable to find an available Jibri, can't start

### ISSUE THREAD

**Issue by davenlin19** [jitsi/jibri#288]
I followed https://www.youtube.com/watch?v=OHHoqKCjJ0E&t=538s and have already installed jitsi in an aws ec2 instance and jibri in another instance.

Now the meeting works on the domain https://class.beeclear.app and the recording button is visible as well.

But when I click on "Recording", it didn't work.
This is the jicofo log:
```
Jicofo 2020-05-07 08:40:27.929 INFO: [65] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().401 Focus request for room: toto@conference.class.beeclear.app
Jicofo 2020-05-07 08:40:27.930 INFO: [65] org.jitsi.jicofo.FocusManager.log() Created new focus for toto@conference.class.beeclear.app@auth.class.beeclear.app. Conference count 1,options: 
Jicofo 2020-05-07 08:40:27.930 INFO: [65] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Joining the room: toto@conference.class.beeclear.app
Jicofo 2020-05-07 08:40:28.074 INFO: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@a4b8e26 member=ChatMember[toto@conference.class.beeclear.app/a83b253d, jid: null]@152284230]
Jicofo 2020-05-07 08:40:28.076 INFO: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Granted owner to toto@conference.class.beeclear.app/a83b253d
Jicofo 2020-05-07 08:40:28.076 INFO: [28] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member toto@conference.class.beeclear.app/a83b253d joined.
Jicofo 2020-05-07 08:40:32.720 SEVERE: [85] org.jitsi.jicofo.recording.jibri.JibriSession.log() Unable to find an available Jibri, can't start
Jicofo 2020-05-07 08:40:32.720 INFO: [85] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Failed to start a Jibri session, no Jibris available
```

and about jibri:
```
2020-05-07 08:41:07.219 INFO: [1] org.jitsi.jibri.Main.main() Jibri run with args [--config, /etc/jitsi/jibri/config.json]
2020-05-07 08:41:07.227 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
2020-05-07 08:41:07.227 INFO: [1] org.jitsi.jibri.Main.main() Using port 3333 for internal HTTP API
2020-05-07 08:41:07.227 INFO: [1] org.jitsi.jibri.Main.main() Using port 2222 for the HTTP API
2020-05-07 08:41:07.883 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed config:
JibriConfig(recordingDirectory=/srv/recordings, singleUseMode=false, enabledStatsD=true, finalizeRecordingScriptPath=/path/to/finalize_recording.sh, xmppEnvironments=[XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[class.beeclear.app], xmppDomain=class.beeclear.app, controlLogin=XmppCredentials(domain=auth.class.beeclear.app, username=jibri, password=jibriauthpass), controlMuc=XmppMuc(domain=internal.auth.class.beeclear.app, roomName=JibriBrewery, nickname=jibri-nickname), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.class.beeclear.app, username=recorder, password=jibrirecorderpass), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)])
2020-05-07 08:41:08.459 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored. 
2020-05-07 08:41:08.716 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.updatePresence() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2020-05-07 08:41:08.718 INFO: [1] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@771158fb
2020-05-07 08:41:08.725 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on class.beeclear.app with config XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[class.beeclear.app], xmppDomain=class.beeclear.app, controlLogin=XmppCredentials(domain=auth.class.beeclear.app, username=jibri, password=jibriauthpass), controlMuc=XmppMuc(domain=internal.auth.class.beeclear.app, roomName=JibriBrewery, nickname=jibri-nickname), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.class.beeclear.app, username=recorder, password=jibrirecorderpass), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)
2020-05-07 08:41:08.726 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2020-05-07 08:41:08.744 WARNING: [19] org.jitsi.xmpp.mucclient.MucClient.log() Disabling certificate verification!
2020-05-07 08:41:08.809 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored. 
2020-05-07 08:41:38.754 WARNING: [24] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary() XMPPConnection was not authenticated
2020-05-07 08:41:38.878 SEVERE: [19] org.jitsi.xmpp.mucclient.MucClientManager.log() Failed to initialize and start a MucClient: 
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'class.beeclear.app:5222' failed because: class.beeclear.app/18.140.249.121 exception: java.net.SocketTimeoutException: connect timed out
	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
	at org.jitsi.xmpp.mucclient.MucClient.initializeConnectAndJoin(MucClient.java:277)
	at org.jitsi.xmpp.mucclient.MucClientManager.lambda$addMucClient$0(MucClientManager.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It seems like I have problem with the port 5222 (class.beeclear.app:5222) but I have already opened every ports in the security group of this instance, just for testing!

Do you have any idea how to make it work? Please!

Thank you!

**Comment by richhamseth** [comment]
Hi, even I facing the same problem

**Comment by tripowertechnologies** [comment]
Did you guys found a solution?

**Comment by davenlin19** [comment]
In my case because I used a subdomain class.beeclear.app. So I bought a new cheap domain for jibri and it works.

**Comment by rb3606** [comment]
I have same issue 
@davenlin19 New domain or new server ?
