### ISSUE TITLE
jibri recording error

### ISSUE THREAD

**Issue by daxiondi** [jitsi/jibri#408]
start recording error
jibri log
```
2021-05-20 15:08:21.675 SEVERE: [41] org.openqa.selenium.os.OsProcess.checkForError() org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
2021-05-20 15:08:21.676 SEVERE: [41] org.jitsi.jibri.api.xmpp.XmppApi.log() Error starting Jibri service
org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jitsi.rtctest.7moor.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-143-generic', java.version: '1.8.0_272'
Driver info: driver.version: ChromeDriver
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:190)
        at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:160)
        at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:109)
        at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:103)
        at org.jitsi.jibri.JibriManager.startFileRecording(JibriManager.kt:139)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:300)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq(XmppApi.kt:198)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq(XmppApi.kt:170)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleIq(XmppApi.kt:152)
        at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:569)
        at org.jitsi.xmpp.mucclient.MucClient.access$800(MucClient.java:50)
        at org.jitsi.xmpp.mucclient.MucClient$2.handleIQRequest(MucClient.java:533)
        at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:23717/status] to be available after 20002 ms
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
        ... 23 more
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:148)
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
        ... 24 more 
```

chrome version
```
ii  google-chrome-stable                   90.0.4430.212-1                                 amd64        The web browser from Google
```

chromedriver version
```
ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})
```

**Comment by muratugureminoglu** [comment]
Hi @daxiondi 

Have you solved this issue?

**Comment by daxiondi** [comment]
No, no, I just don't think I'll get my answer, so I shut down pr
