### ISSUE TITLE
Jibri Recording Failed To Start

### ISSUE THREAD

**Issue by ahmetinal7** [jitsi/jibri#431]
Hello i have problem about jibri. Here my jibri logs. I changed my all domain.com to meet.jitsi but still have same problem.

error: Unable to use a TTY - container jibri did not allocate one
If you don't see a command prompt, try pressing enter.
2021-08-23 12:47:05.809 FINE: [77] org.jitsi.xmpp.mucclient.MucClient.log() Received an IQ with type set: IQ Stanza (jibri http://jitsi.org/protocol/jibri) [to=jibri@auth.meet.jitsi/OsnTcxlv,from=jibribrewery@internal.muc.meet.jitsi/focus,id=amlicmlAYXV0aC5tZWV0LmppdHNpL09zblRjeGx2AGd1N2llLTMyMAB9MKAL27uLVhq/q96wolfF,type=set,]
2021-08-23 12:47:05.809 INFO: [77] org.jitsi.jibri.api.xmpp.XmppApi.log() Received JibriIq from environment [MucClient id=localhost hostname=localhost]
2021-08-23 12:47:05.810 INFO: [77] org.jitsi.jibri.api.xmpp.XmppApi.log() Received start request, starting service
2021-08-23 12:47:05.815 INFO: [77] org.jitsi.jibri.api.xmpp.XmppApi.log() Parsed call url info: CallUrlInfo(baseUrl=https://172.18.1.71:30220, callName=123, urlParams=[])
2021-08-23 12:47:05.815 INFO: [77] org.jitsi.jibri.JibriManager.log() Starting a file recording with params: FileRecordingRequestParams(callParams=CallParams(callUrlInfo=CallUrlInfo(baseUrl=https://172.18.1.71:30220, callName=123, urlParams=[]), email='', passcode=null, callStatsUsernameOverride=, displayName=), sessionId=ozxyiwkkejwclvyf, callLoginParams=XmppCredentials(domain=recorder.172.18.1.71, port=null, username=recorder, password=jibrirecorderpass))
2021-08-23 12:47:05.816 FINE: [77] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.log() Detected os as OS: LINUX
2021-08-23 12:47:05.817 FINE: [77] org.jitsi.jibri.config.log() ConfigSourceSupplier: Trying to retrieve key 'jibri.chrome.flags' from source 'config' as type kotlin.collections.List<kotlin.String>
2021-08-23 12:47:05.817 FINE: [77] org.jitsi.jibri.config.log() ConfigSourceSupplier: Successfully retrieved key 'jibri.chrome.flags' from source 'config' as type kotlin.collections.List<kotlin.String>
Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 13719
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2021-08-23 12:47:06.173 INFO: [77] org.openqa.selenium.remote.ProtocolHandshake.createSession() Detected dialect: OSS
2021-08-23 12:47:06.179 FINE: [77] org.jitsi.jibri.config.log() FallbackSupplier: checking for value via suppliers:
LambdaSupplier: 'JibriConfig::recordingDirectory'
ConfigSourceSupplier: key: 'jibri.recording.recordings-directory', type: 'kotlin.String', source: 'config'
2021-08-23 12:47:06.179 FINE: [77] org.jitsi.jibri.config.log() LambdaSupplier: Trying to retrieve value via JibriConfig::recordingDirectory
2021-08-23 12:47:06.179 FINE: [77] org.jitsi.jibri.config.log() LambdaSupplier: 'JibriConfig::recordingDirectory': found value
2021-08-23 12:47:06.179 FINE: [77] org.jitsi.jibri.config.log() FallbackSupplier: value found via LambdaSupplier: 'JibriConfig::recordingDirectory'
2021-08-23 12:47:06.180 FINE: [77] org.jitsi.jibri.config.log() FallbackSupplier: checking for value via suppliers:
LambdaSupplier: 'JibriConfig::finalizeRecordingScriptPath'
ConfigSourceSupplier: key: 'jibri.recording.finalize-script', type: 'kotlin.String', source: 'config'
2021-08-23 12:47:06.180 FINE: [77] org.jitsi.jibri.config.log() LambdaSupplier: Trying to retrieve value via JibriConfig::finalizeRecordingScriptPath
2021-08-23 12:47:06.180 FINE: [77] org.jitsi.jibri.config.log() LambdaSupplier: 'JibriConfig::finalizeRecordingScriptPath': found value
2021-08-23 12:47:06.180 FINE: [77] org.jitsi.jibri.config.log() FallbackSupplier: value found via LambdaSupplier: 'JibriConfig::finalizeRecordingScriptPath'
2021-08-23 12:47:06.180 INFO: [77] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Writing recording to /config/recordings/ozxyiwkkejwclvyf, finalize script path /config/finalize.sh
2021-08-23 12:47:06.181 FINE: [77] org.jitsi.jibri.statsd.JibriStatsDClient.log() Incrementing statsd counter: start:recording
2021-08-23 12:47:06.181 INFO: [77] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: IDLE -> BUSY
2021-08-23 12:47:06.181 FINE: [77] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-08-23 12:47:06.181 INFO: [77] org.jitsi.jibri.api.xmpp.XmppApi.log() Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2021-08-23 12:47:06.182 FINE: [77] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@161957f0
2021-08-23 12:47:06.182 FINE: [77] org.jitsi.xmpp.mucclient.MucClientManager.log() Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@77578641
2021-08-23 12:47:06.182 INFO: [77] org.jitsi.jibri.api.xmpp.XmppApi.log() Sending 'pending' response to start IQ
2021-08-23 12:47:06.183 INFO: [76] org.jitsi.jibri.selenium.pageobjects.HomePage.log() Visiting url https://172.18.1.71:30220
2021-08-23 12:47:06.184 FINE: [38] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2021-08-23 12:47:06.188 FINE: [38] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
2021-08-23 12:47:06.858 INFO: [76] org.jitsi.jibri.selenium.pageobjects.HomePage.log() Waited 675ms for driver to load page
2021-08-23 12:47:06.873 SEVERE: [76] org.jitsi.jibri.selenium.JibriSelenium.log() An error occurred while joining the call
org.openqa.selenium.WebDriverException: : Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
(Session info: chrome=90.0.4430.212)
(Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 5.4.0-77-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jitsi-deneme-68b8f8b448-sst2z', ip: '10.34.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '1.8.0_292'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.GHOl1e}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:39407}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 90.0.4430.212, webStorageEnabled: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 8ad4614eecfdb3f06f9264d027e395c9
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
at org.jitsi.jibri.selenium.JibriSelenium.setLocalStorageValues(JibriSelenium.kt:202)
at org.jitsi.jibri.selenium.JibriSelenium.access$setLocalStorageValues(JibriSelenium.kt:158)
at org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:300)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2021-08-23 12:47:06.873 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
2021-08-23 12:47:06.874 INFO: [76] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() File recording service transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
2021-08-23 12:47:06.874 INFO: [76] org.jitsi.jibri.api.xmpp.XmppApi.log() Current service had an error Error: FailedToJoinCall SESSION Failed to join the call, sending error iq
2021-08-23 12:47:06.874 FINE: [76] org.jitsi.jibri.statsd.JibriStatsDClient.log() Incrementing statsd counter: stop:recording
2021-08-23 12:47:06.875 INFO: [76] org.jitsi.jibri.JibriManager.log() Stopping the current service
2021-08-23 12:47:06.875 INFO: [76] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Stopping capturer
2021-08-23 12:47:06.875 INFO: [76] org.jitsi.jibri.util.JibriSubprocess.log() Stopping ffmpeg process
2021-08-23 12:47:06.876 INFO: [76] org.jitsi.jibri.util.JibriSubprocess.log() ffmpeg exited with value null
2021-08-23 12:47:06.876 INFO: [76] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Quitting selenium
2021-08-23 12:47:06.885 INFO: [76] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Participants in this recording: []
2021-08-23 12:47:06.889 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Leaving call and quitting browser
2021-08-23 12:47:06.889 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Recurring call status checks cancelled
2021-08-23 12:47:06.897 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Got 3 log entries for type browser
2021-08-23 12:47:06.905 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Got 114 log entries for type driver
2021-08-23 12:47:06.919 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Got 0 log entries for type client
2021-08-23 12:47:06.919 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Leaving web call
2021-08-23 12:47:06.933 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Quitting chrome driver
2021-08-23 12:47:07.002 INFO: [76] org.jitsi.jibri.selenium.JibriSelenium.log() Chrome driver quit
2021-08-23 12:47:07.002 INFO: [76] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Finalizing the recording
2021-08-23 12:47:07.004 SEVERE: [76] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Failed to run finalize script
java.io.IOException: Cannot run program "/config/finalize.sh": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at org.jitsi.jibri.util.ProcessWrapper.start(ProcessWrapper.kt:88)
at org.jitsi.jibri.service.impl.FileRecordingJibriService.finalize(FileRecordingJibriService.kt:220)
at org.jitsi.jibri.service.impl.FileRecordingJibriService.stop(FileRecordingJibriService.kt:205)
at org.jitsi.jibri.JibriManager.stopService(JibriManager.kt:263)
at org.jitsi.jibri.JibriManager$startService$1.invoke(JibriManager.kt:211)
at org.jitsi.jibri.JibriManager$startService$1.invoke(JibriManager.kt:85)
at org.jitsi.jibri.util.StatusPublisher$addStatusHandler$1.invoke(StatusPublisher.kt:37)
at org.jitsi.jibri.util.StatusPublisher$addStatusHandler$1.invoke(StatusPublisher.kt:29)
at org.jitsi.jibri.util.StatusPublisher$publishStatus$1.invoke(StatusPublisher.kt:53)
at org.jitsi.jibri.util.StatusPublisher$publishStatus$1.invoke(StatusPublisher.kt:29)
at kotlin.collections.CollectionsKt__MutableCollectionsKt.filterInPlace$CollectionsKt__MutableCollectionsKt(MutableCollections.kt:285)
at kotlin.collections.CollectionsKt__MutableCollectionsKt.retainAll(MutableCollections.kt:276)
at org.jitsi.jibri.util.StatusPublisher.publishStatus(StatusPublisher.kt:53)
at org.jitsi.jibri.service.impl.StatefulJibriService.onServiceStateChange(StatefulJibriService.kt:40)
at org.jitsi.jibri.service.impl.StatefulJibriService.access$onServiceStateChange(StatefulJibriService.kt:26)
at org.jitsi.jibri.service.impl.StatefulJibriService$1.invoke(StatefulJibriService.kt:35)
at org.jitsi.jibri.service.impl.StatefulJibriService$1.invoke(StatefulJibriService.kt:26)
at org.jitsi.jibri.util.NotifyingStateMachine.notify(NotifyingStateMachine.kt:26)
at org.jitsi.jibri.service.JibriServiceStateMachine.access$notify(JibriServiceStateMachine.kt:46)
at org.jitsi.jibri.service.JibriServiceStateMachine$stateMachine$1$5.invoke(JibriServiceStateMachine.kt:100)
at org.jitsi.jibri.service.JibriServiceStateMachine$stateMachine$1$5.invoke(JibriServiceStateMachine.kt:46)
at com.tinder.StateMachine.notifyOnTransition(StateMachine.kt:65)
at com.tinder.StateMachine.transition(StateMachine.kt:23)
at org.jitsi.jibri.service.JibriServiceStateMachine.transition(JibriServiceStateMachine.kt:112)
at org.jitsi.jibri.service.impl.StatefulJibriService$registerSubComponent$1.invoke(StatefulJibriService.kt:46)
at org.jitsi.jibri.service.impl.StatefulJibriService$registerSubComponent$1.invoke(StatefulJibriService.kt:26)
at org.jitsi.jibri.util.StatusPublisher$addStatusHandler$1.invoke(StatusPublisher.kt:37)
at org.jitsi.jibri.util.StatusPublisher$addStatusHandler$1.invoke(StatusPublisher.kt:29)
at org.jitsi.jibri.util.StatusPublisher$publishStatus$1.invoke(StatusPublisher.kt:53)
at org.jitsi.jibri.util.StatusPublisher$publishStatus$1.invoke(StatusPublisher.kt:29)
at kotlin.collections.CollectionsKt__MutableCollectionsKt.filterInPlace$CollectionsKt__MutableCollectionsKt(MutableCollections.kt:285)
at kotlin.collections.CollectionsKt__MutableCollectionsKt.retainAll(MutableCollections.kt:276)
at org.jitsi.jibri.util.StatusPublisher.publishStatus(StatusPublisher.kt:53)
at org.jitsi.jibri.selenium.JibriSelenium.onSeleniumStateChange(JibriSelenium.kt:208)
at org.jitsi.jibri.selenium.JibriSelenium.access$onSeleniumStateChange(JibriSelenium.kt:158)
at org.jitsi.jibri.selenium.JibriSelenium$1.invoke(JibriSelenium.kt:193)
at org.jitsi.jibri.selenium.JibriSelenium$1.invoke(JibriSelenium.kt:158)
at org.jitsi.jibri.util.NotifyingStateMachine.notify(NotifyingStateMachine.kt:26)
at org.jitsi.jibri.selenium.SeleniumStateMachine.access$notify(SeleniumStateMachine.kt:33)
at org.jitsi.jibri.selenium.SeleniumStateMachine$stateMachine$1$5.invoke(SeleniumStateMachine.kt:78)
at org.jitsi.jibri.selenium.SeleniumStateMachine$stateMachine$1$5.invoke(SeleniumStateMachine.kt:33)
at com.tinder.StateMachine.notifyOnTransition(StateMachine.kt:65)
at com.tinder.StateMachine.transition(StateMachine.kt:23)
at org.jitsi.jibri.selenium.SeleniumStateMachine.transition(SeleniumStateMachine.kt:83)
at org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:311)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 50 more
2021-08-23 12:47:07.005 INFO: [76] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: BUSY -> IDLE
2021-08-23 12:47:07.006 FINE: [76] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-08-23 12:47:07.006 INFO: [76] org.jitsi.jibri.api.xmpp.XmppApi.log() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2021-08-23 12:47:07.007 FINE: [76] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@b181234
2021-08-23 12:47:07.007 FINE: [76] org.jitsi.xmpp.mucclient.MucClientManager.log() Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@161957f0
2021-08-23 12:47:07.010 FINE: [38] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2021-08-23 12:47:07.011 FINE: [38] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
2021-08-23 12:47:42.133 FINE: [17] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-08-23 12:48:42.133 FINE: [17] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-08-23 12:49:42.133 FINE: [17] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-08-23 12:50:42.133 FINE: [17] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status

**Comment by raluca8x8** [comment]
Hi, have you tried the solution posted in https://github.com/jitsi/jibri/issues/240?

**Comment by ahmetinal7** [comment]
> Hi, have you tried the solution posted in #240?

Yes, i tried but still have same problem...

**Comment by ahmetinal7** [comment]
After i changed some stuff in env file i got different error.
`	at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginInternal(XMPPTCPConnection.java:444)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:491)
	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:448)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:681)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from jibribrewery@internal.muc.meet.jitsi/jibri-instanse-347544113: XMPPError: not-allowed - cancel
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:132)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:263)
	at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:355)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:498)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:444)
	at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.join(MucClient.java:769)
	at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.access$700(MucClient.java:698)
	at org.jitsi.xmpp.mucclient.MucClient.joinMucs(MucClient.java:389)
	at org.jitsi.xmpp.mucclient.MucClient.access$200(MucClient.java:50)
	at org.jitsi.xmpp.mucclient.MucClient$1.authenticated(MucClient.java:283)
	... 15 more`

**Comment by alkanpolat** [comment]
Can you try turning off the firewall?

sudo disable ufw

If it works like this, it means you have not allowed the relevant ports.
