### ISSUE TITLE
No configuration setting found for key 'randomize-control-muc-nickname'

### ISSUE THREAD

**Issue by emrahcom** [jitsi/jibri#456]
## Description
The current stable `jibri` (_8.0-113-g56bf495-1_) doesn't work without `randomize-control-muc-nickname` in `jibri.conf` and there is no info in [example_xmpp_envs.conf](https://github.com/jitsi/jibri/blob/master/doc/example_xmpp_envs.conf) related with this param

## Current behavior
`jibri` service throws the following error message in `systemd` status and doesn't work

```
Exception in thread "main" org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: No suppliers found a value:                                                  
  org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: Considering empty XMPP envs list as not found                                                         
  org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: /etc/jitsi/jibri/jibri.conf: 41: No configuration setting found for key 'randomize-control-muc-nickname'                        
        at org.jitsi.metaconfig.supplier.FallbackSupplier.doGet(FallbackSupplier.kt:57)                                                                                 
        at org.jitsi.metaconfig.supplier.ConfigValueSupplier$value$2.invoke(ConfigValueSupplier.kt:30)                                                                  
        at org.jitsi.metaconfig.supplier.ConfigValueSupplier$value$2.invoke(ConfigValueSupplier.kt:29)                                                                  
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)                                                                                                          
        at org.jitsi.metaconfig.supplier.ConfigValueSupplier.getValue(ConfigValueSupplier.kt)                                                                           
        at org.jitsi.metaconfig.supplier.ConfigValueSupplier.get(ConfigValueSupplier.kt:32)                                                                             
        at org.jitsi.jibri.MainKt.main(Main.kt:141)
```

## Expected Behavior
`randomize-control-muc-nickname` in example config or running as expected without this param

## Steps to reproduce
Use the current stable without `randomize-control-muc-nickname` in `jibri.conf`

# Environment details
Debian 11 Bullseye
openjdk-11-jre-headless 11.0.13+8-1~deb11u1
jibri 8.0-113-g56bf495-1

**Comment by damencho** [comment]
Ups.

**Comment by damencho** [comment]
@emrahcom I just pushed the next version 8.0-114 to stable, I had forgotten about this ... sorry. Should be fine now.

**Comment by damencho** [comment]
Thanks for the report.

**Comment by darsv** [comment]
Just updated to 8.0-114, but not able to stream

This is the log

```
2021-12-09 11:18:07.976 INFORMACIÓN: [1] MainKt.handleCommandLineArgs#185: Jibri run with args [--config, /etc/jitsi/jibri/config.json]
2021-12-09 11:18:08.028 INFORMACIÓN: [1] MainKt.setupLegacyConfig#210: Checking legacy config file /etc/jitsi/jibri/config.json
2021-12-09 11:18:08.028 INFORMACIÓN: [1] MainKt.setupLegacyConfig#213: Legacy config file /etc/jitsi/jibri/config.json doesn't exist
2021-12-09 11:18:08.247 INFORMACIÓN: [1] MainKt.main#55: Jibri starting up with id 
2021-12-09 11:18:08.542 INFORMACIÓN: [1] JwtInfo$Companion.fromConfig#154: got jwtConfig: {}

2021-12-09 11:18:08.542 INFORMACIÓN: [1] JwtInfo$Companion.fromConfig#164: Unable to create JwtInfo: com.typesafe.config.ConfigException$Missing: reference.conf @ jar:file:/opt/jitsi/jibri/jibri.jar!/reference.conf: 62: No configuration setting found for key 'signing-key-path'
2021-12-09 11:18:08.666 INFORMACIÓN: [1] MainKt.main#125: Using port 3333 for internal HTTP API
2021-12-09 11:18:08.672 DETALLADO: [26] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
2021-12-09 11:18:08.883 INFORMACIÓN: [1] XmppApi.updatePresence#144: Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2021-12-09 11:18:08.891 INFORMACIÓN: [1] MainKt.main#151: Using port 2222 for HTTP API
2021-12-09 11:19:08.663 DETALLADO: [26] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
2021-12-09 11:20:08.663 DETALLADO: [26] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
2021-12-09 11:21:08.663 DETALLADO: [26] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
2021-12-09 11:22:08.663 DETALLADO: [26] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
```

**Comment by emrahcom** [comment]
It works for me with this [jibri.conf](https://github.com/jitsi-contrib/installers/blob/main/templates/jibri/etc/jitsi/jibri/jibri.conf)
