### ISSUE TITLE
Error Starting Live Stream

### ISSUE THREAD

**Issue by subsub** [jitsi/jibri#53]
I finally have made it to this state where I can put stream key to start live streaming. I use youtube stream key to do this. But whenever I try to do live stream it fails. Here's log output from jibri service:
```bash
-- Logs begin at Kam 2017-11-02 08:51:55 WIB, end at Kam 2017-11-02 09:08:56 WIB. --
Nov 02 08:53:46 jibri app.py[1773]: 2017-11-02 08:53:46,491 INFO     Creating a client for hostname: my.domain.com with options: {'selenium_xmpp_login': 'recorder@recorder.my.domain.com', 'password': 'mypassword', 'jid_username': 'jibri', 'mucserver_prefix': 'conference.', 'jidserver_prefix': 'auth.', 'boshdomain_prefix': 'recorder.', 'recording_directory': './recordings', 'boshdomain': 'recorder.my.domain.com', 'selenium_xmpp_username': 'recorder', 'room': 'TheBrewery@conference.my.domain.com', 'jid': 'jibri@auth.my.domain.com', 'xmpp_domain': 'my.domain.com', 'nick': 'jibri-0072226489578415265', 'selenium_xmpp_password': 'mypassword', 'usage_timeout': 0, 'roompass': '', 'roomname': 'TheBrewery', 'brewery_prefix': 'conference.', 'selenium_xmpp_prefix': 'recorder.', 'url': 'https://my.domain.com/%SUBDOMAIN%%ROOM%'}
Nov 02 08:53:46 jibri app.py[1773]: 2017-11-02 08:53:46,498 INFO     jibri_watcher starting up...
Nov 02 08:53:46 jibri app.py[1773]: 2017-11-02 08:53:46,627 INFO      * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Nov 02 08:53:46 jibri app.py[1773]: 2017-11-02 08:53:46,662 WARNING  jid property deprecated. Use boundjid.bare
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,136 INFO     Negotiating TLS
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,137 INFO     Using SSL version: TLS 1.0
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,209 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,501 INFO     JID set to: jibri@auth.my.domain.com/2e7d9ea0-9538-4d01-9b0b-efd825a2fae9
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,522 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,523 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7f3cfb1bbbe0>, connecting to room TheBrewery@conference.my.domain.com as jibri-0072226489578415265
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,548 INFO     sending presence: <presence to="TheBrewery@conference.my.domain.com" xml:lang="en"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="idle" /></presence>
Nov 02 08:53:47 jibri app.py[1773]: 2017-11-02 08:53:47,552 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7f3cfb1bbbe0>
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,504 INFO     on_jibri_iq: <iq from="thebrewery@conference.my.domain.com/focus" to="jibri@auth.my.domain.com/2e7d9ea0-9538-4d01-9b0b-efd825a2fae9" id="amlicmlAYXV0aC50c3QuZWRwbHVzLmJpei8yZTdkOWVhMC05NTM4LTRkMDEtOWIwYi1lZmQ4MjVhMmZhZTkAU1dPNXctODYxOTcAfGj5zxYb8haA9jrz8CkCzw==" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" action="start" room="test@conference.my.domain.com" streamid="youtube-stream-key" recording_mode="stream" /></iq>
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,512 INFO     sending presence: <presence to="TheBrewery@conference.my.domain.com" xml:lang="en"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="busy" /></presence>
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,514 INFO     Client options for host: {'selenium_xmpp_login': 'recorder@recorder.my.domain.com', 'password': 'mypassword', 'jid_username': 'jibri', 'mucserver_prefix': 'conference.', 'jidserver_prefix': 'auth.', 'boshdomain_prefix': 'recorder.', 'recording_directory': './recordings', 'boshdomain': 'recorder.my.domain.com', 'selenium_xmpp_username': 'recorder', 'room': 'TheBrewery@conference.my.domain.com', 'jid': 'jibri@auth.my.domain.com', 'xmpp_domain': 'my.domain.com', 'nick': 'jibri-0072226489578415265', 'selenium_xmpp_password': 'mypassword', 'usage_timeout': 0, 'roompass': '', 'roomname': 'TheBrewery', 'brewery_prefix': 'conference.', 'selenium_xmpp_prefix': 'recorder.', 'url': 'https://my.domain.com/%SUBDOMAIN%%ROOM%'}
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,515 INFO     Setting xmpp login from client options: recorder@recorder.my.domain.com
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,516 INFO     Setting xmpp password from client options
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,516 INFO     Setting boshdomain from client options recorder.my.domain.com
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,516 INFO     Setting xmpp_domain from client options my.domain.com
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,517 INFO     Setting mucserver_prefix from client options conference.
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,517 INFO     Setting recording_directory from client options ./recordings
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,522 INFO     Start recording callback
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,522 INFO     update_jibri_status
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,522 INFO     looping through queue for host my.domain.com
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,523 INFO     Starting jibri
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,523 INFO     Starting selenium attempt 1/3 pjsua_flag:False
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,525 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 08:57:09 jibri app.py[1773]: 2017-11-02 08:57:09,525 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 08:57:39 jibri app.py[1773]: 2017-11-02 08:57:39,577 ERROR    Jibri Startup exception during attempt 1/3: Remote end closed connection without response
Nov 02 08:57:39 jibri app.py[1773]: 2017-11-02 08:57:39,583 INFO     start_jibri_selenium returned retcode=9999 during attempt 1/3
Nov 02 08:57:39 jibri app.py[1773]: 2017-11-02 08:57:39,584 INFO     Starting selenium attempt 2/3 pjsua_flag:False
Nov 02 08:57:39 jibri app.py[1773]: 2017-11-02 08:57:39,585 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 08:57:39 jibri app.py[1773]: 2017-11-02 08:57:39,586 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 08:58:09 jibri app.py[1773]: 2017-11-02 08:58:09,612 ERROR    Jibri Startup exception during attempt 2/3: Remote end closed connection without response
Nov 02 08:58:09 jibri app.py[1773]: 2017-11-02 08:58:09,620 INFO     start_jibri_selenium returned retcode=9999 during attempt 2/3
Nov 02 08:58:09 jibri app.py[1773]: 2017-11-02 08:58:09,622 INFO     Starting selenium attempt 3/3 pjsua_flag:False
Nov 02 08:58:09 jibri app.py[1773]: 2017-11-02 08:58:09,623 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 08:58:09 jibri app.py[1773]: 2017-11-02 08:58:09,623 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,634 ERROR    Jibri Startup exception during attempt 3/3: Remote end closed connection without response
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,638 INFO     start_jibri_selenium returned retcode=9999 during attempt 3/3
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,640 INFO     start_jibri_selenium returned retcode=9999
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,641 INFO     jibri_stop_callback run with status startup_selenium_error
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,641 INFO     queueing error error|startup_selenium_error for host my.domain.com
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,642 INFO     queueing job for jibri_watcher
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,642 INFO     jibri_watcher received job, now watching ffmpeg and selenium with a timeout of 0.
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,642 INFO     jibri_watcher finished loop...
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,642 INFO     jibri_watcher starting up...
Nov 02 08:58:39 jibri app.py[1773]: chrome: no process found
Nov 02 08:58:39 jibri app.py[1773]: chromedriver: no process found
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,724 INFO     got msg from main: error|startup_selenium_error
Nov 02 08:58:39 jibri app.py[1773]: 2017-11-02 08:58:39,730 INFO     sending status update: <iq to="thebrewery@conference.my.domain.com/focus" id="583e6e71-763b-4e7c-9601-3f1befa1b4b5-7" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" status="failed"><error xmlns="jabber:client" code="504" type="wait"><remote-server-timeout xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Startup error: Selenium error</text><retry xmlns="http://jitsi.org/protocol/jibri" /></error></jibri></iq>
Nov 02 08:58:40 jibri app.py[1773]: 2017-11-02 08:58:40,711 ERROR    Exception in callback jibri_start_callback(<jibrixmppcli...x7f3cfb1bbbe0>, '', 'stream', 'youtube-stream-key', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310
Nov 02 08:58:40 jibri app.py[1773]: handle: <Handle jibri_start_callback(<jibrixmppcli...x7f3cfb1bbbe0>, '', 'stream', 'youtube-stream-key', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310>
Nov 02 08:58:40 jibri app.py[1773]: Traceback (most recent call last):
Nov 02 08:58:40 jibri app.py[1773]:   File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
Nov 02 08:58:40 jibri app.py[1773]:     self._callback(*self._args)
Nov 02 08:58:40 jibri app.py[1773]:   File "/home/jibri/jibri-xmpp-client/app.py", line 521, in jibri_start_callback
Nov 02 08:58:40 jibri app.py[1773]:     jibri_stop_callback('startup_selenium_error')
Nov 02 08:58:40 jibri app.py[1773]:   File "/home/jibri/jibri-xmpp-client/app.py", line 794, in jibri_stop_callback
Nov 02 08:58:40 jibri app.py[1773]:     finalize_recording()
Nov 02 08:58:40 jibri app.py[1773]:   File "/home/jibri/jibri-xmpp-client/app.py", line 203, in finalize_recording
Nov 02 08:58:40 jibri app.py[1773]:     call([finalize_recording_script,recording_directory])
Nov 02 08:58:40 jibri app.py[1773]:   File "/usr/lib/python3.5/subprocess.py", line 557, in call
Nov 02 08:58:40 jibri app.py[1773]:     with Popen(*popenargs, **kwargs) as p:
Nov 02 08:58:40 jibri app.py[1773]:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
Nov 02 08:58:40 jibri app.py[1773]:     restore_signals, start_new_session)
Nov 02 08:58:40 jibri app.py[1773]:   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
Nov 02 08:58:40 jibri app.py[1773]:     raise child_exception_type(errno_num, err_msg)
Nov 02 08:58:40 jibri app.py[1773]: PermissionError: [Errno 13] Permission denied
Nov 02 08:59:09 jibri app.py[1773]: 2017-11-02 08:59:09,741 WARNING  Timed out waiting for IqWait_583e6e71-763b-4e7c-9601-3f1befa1b4b5-7
Nov 02 08:59:09 jibri app.py[1773]: 2017-11-02 08:59:09,744 ERROR    Failed to send status update: <iq to="thebrewery@conference.my.domain.com/focus" id="583e6e71-763b-4e7c-9601-3f1befa1b4b5-7" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" status="failed"><error xmlns="jabber:client" code="504" type="wait"><remote-server-timeout xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Startup error: Selenium error</text><retry xmlns="http://jitsi.org/protocol/jibri" /></error></jibri></iq>
```

Please help.
Thank you

**Comment by subsub** [comment]
I don't know if this is related but when I run the test for jibri selenium side, it returns error:
```bash
Initializing Driver
2017-11-02 09:26:25,967 DEBUG    POST http://127.0.0.1:58776/session {"desiredCapabilities": {"version": "", "loggingPrefs": {"browser": "ALL"}, "platform": "ANY", "javascriptEnabled": true, "chromeOptions": {"extensions": [], "args": ["--use-fake-ui-for-media-stream", "--start-maximized", "--kiosk", "--enabled", "--enable-logging", "--vmodule=*=3", "--disable-infobars", "--alsa-output-device=plug:amix"]}, "browserName": "chrome"}}
2017-11-02 09:27:26,007 DEBUG    Finished Request
Traceback (most recent call last):
  File "./jibriselenium.py", line 324, in <module>
    js = JibriSeleniumDriver(URL,token,displayname=displayname,email=email,pjsua_flag=pjsua_flag)
  File "./jibriselenium.py", line 69, in __init__
    self.initDriver()
  File "./jibriselenium.py", line 83, in initDriver
    self.driver = webdriver.Chrome(chrome_options=options, desired_capabilities=desired_capabilities)
  File "/home/jibri/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 67, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/jibri/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 91, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/jibri/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 178, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/jibri/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 237, in execute
    self.error_handler.check_response(response)
  File "/home/jibri/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-98-generic x86_64)
```

**Comment by subsub** [comment]
Turns out the [above error](https://github.com/jitsi/jibri/issues/53#issuecomment-341300467) is error from google chrome latest stable release which requires nss version 3.26.
Fix the test by updating nss library using `sudo apt-get install --reinstall libnss3`. Now the test success.
But this doesn't fix live stream failure issue.

**Comment by saghul** [comment]
Do you still get that traceback?

**Comment by subsub** [comment]
@saghul Yes, but with different error. Now it's audio check that cause an error, and I don't know how to fix.
Here's the log:
```bash
-- Logs begin at Kam 2017-11-02 11:54:21 WIB, end at Kam 2017-11-02 13:48:07 WIB. --
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,013 INFO     Creating a client for hostname: my.domain.com with options: {'jidserver_prefix': 'auth.', 'selenium_xmpp_login': 'recorder@recorder.my.domain.com', 'boshdomain': 'recorder.my.domain.com', 'jid_username': 'jibri', 'usage_timeout': 0, 'selenium_xmpp_password': 'mypassword', 'roomname': 'TheBrewery', 'selenium_xmpp_prefix': 'recorder.', 'password': 'mypassword', 'roompass': '', 'brewery_prefix': 'conference.', 'mucserver_prefix': 'conference.', 'boshdomain_prefix': 'recorder.', 'nick': 'jibri-41832950736615837', 'xmpp_domain': 'my.domain.com', 'selenium_xmpp_username': 'recorder', 'url': 'https://my.domain.com/%SUBDOMAIN%%ROOM%', 'recording_directory': './recordings', 'room': 'TheBrewery@conference.my.domain.com', 'jid': 'jibri@auth.my.domain.com'}
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,017 INFO     jibri_watcher starting up...
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,115 INFO      * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,152 WARNING  jid property deprecated. Use boundjid.bare
Nov 02 13:22:36 jibri app.py[3473]: 2017-11-02 13:22:36,562 INFO     Negotiating TLS
Nov 02 13:22:36 jibri app.py[3473]: 2017-11-02 13:22:36,563 INFO     Using SSL version: TLS 1.0
Nov 02 13:22:36 jibri app.py[3473]: 2017-11-02 13:22:36,707 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,769 INFO     JID set to: jibri@auth.my.domain.com/8a985663-a5a4-4aab-a881-a73b22bad4f6
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,831 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,832 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>, connecting to room TheBrewery@conference.my.domain.com as jibri-41832950736615837
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,889 INFO     sending presence: <presence xml:lang="en" to="TheBrewery@conference.my.domain.com"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="idle" /></presence>
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,893 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,208 INFO     on_jibri_iq: <iq to="jibri@auth.my.domain.com/8a985663-a5a4-4aab-a881-a73b22bad4f6" id="amlicmlAYXV0aC50c3QuZWRwbHVzLmJpei84YTk4NTY2My1hNWE0LTRhYWItYTg4MS1hNzNiMjJiYWQ0ZjYAU1dPNXctOTQ3ODAAfGj5zxYb8haA9jrz8CkCzw==" from="thebrewery@conference.my.domain.com/focus" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" recording_mode="stream" streamid="youtube-stream-key" room="test@conference.my.domain.com" action="start" /></iq>
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,213 INFO     sending presence: <presence xml:lang="en" to="TheBrewery@conference.my.domain.com"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="busy" /></presence>
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,214 INFO     Client options for host: {'jidserver_prefix': 'auth.', 'selenium_xmpp_login': 'recorder@recorder.my.domain.com', 'boshdomain': 'recorder.my.domain.com', 'jid_username': 'jibri', 'usage_timeout': 0, 'selenium_xmpp_password': 'mypassword', 'roomname': 'TheBrewery', 'selenium_xmpp_prefix': 'recorder.', 'password': 'mypassword', 'roompass': '', 'brewery_prefix': 'conference.', 'mucserver_prefix': 'conference.', 'boshdomain_prefix': 'recorder.', 'nick': 'jibri-41832950736615837', 'xmpp_domain': 'my.domain.com', 'selenium_xmpp_username': 'recorder', 'url': 'https://my.domain.com/%SUBDOMAIN%%ROOM%', 'recording_directory': './recordings', 'room': 'TheBrewery@conference.my.domain.com', 'jid': 'jibri@auth.my.domain.com'}
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting xmpp login from client options: recorder@recorder.my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting xmpp password from client options
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting boshdomain from client options recorder.my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting xmpp_domain from client options my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,216 INFO     Setting mucserver_prefix from client options conference.
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,216 INFO     Setting recording_directory from client options ./recordings
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     Start recording callback
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     update_jibri_status
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     looping through queue for host my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     Starting jibri
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     Starting selenium attempt 1/3 pjsua_flag:False
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,227 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,227 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,516 WARNING  ERROR: failed audio check, no audio levels detected: 1
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,520 WARNING  jibri detected audio issues during startup, bailing out.
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,525 INFO     start_jibri_selenium returned retcode=3 during attempt 1/3
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,525 INFO     Starting selenium attempt 2/3 pjsua_flag:False
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,526 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,526 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,475 WARNING  ERROR: failed audio check, no audio levels detected: 1
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,480 WARNING  jibri detected audio issues during startup, bailing out.
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,481 INFO     start_jibri_selenium returned retcode=3 during attempt 2/3
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,481 INFO     Starting selenium attempt 3/3 pjsua_flag:False
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,481 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,484 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,430 WARNING  ERROR: failed audio check, no audio levels detected: 1
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,436 WARNING  jibri detected audio issues during startup, bailing out.
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,441 INFO     start_jibri_selenium returned retcode=3 during attempt 3/3
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,441 INFO     start_jibri_selenium returned retcode=3
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,441 INFO     jibri_stop_callback run with status startup_selenium_error
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,442 INFO     queueing error error|startup_selenium_error for host my.domain.com
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,442 INFO     queueing job for jibri_watcher
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,443 INFO     jibri_watcher received job, now watching ffmpeg and selenium with a timeout of 0.
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,443 INFO     jibri_watcher finished loop...
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,444 INFO     jibri_watcher starting up...
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,956 INFO     got msg from main: error|startup_selenium_error
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,963 INFO     sending status update: <iq to="thebrewery@conference.my.domain.com/focus" id="2d179cbd-deeb-4b2d-b052-28c1099f9ef8-7" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" status="failed"><error xmlns="jabber:client" code="504" type="wait"><remote-server-timeout xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Startup error: Selenium error</text><retry xmlns="http://jitsi.org/protocol/jibri" /></error></jibri></iq>
Nov 02 13:24:27 jibri app.py[3473]: 2017-11-02 13:24:27,646 ERROR    Exception in callback jibri_start_callback(<jibrixmppcli...x7f3b957afbe0>, '', 'stream', 'youtube-stream-key', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310
Nov 02 13:24:27 jibri app.py[3473]: handle: <Handle jibri_start_callback(<jibrixmppcli...x7f3b957afbe0>, '', 'stream', 'youtube-stream-key', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310>
Nov 02 13:24:27 jibri app.py[3473]: Traceback (most recent call last):
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
Nov 02 13:24:27 jibri app.py[3473]:     self._callback(*self._args)
Nov 02 13:24:27 jibri app.py[3473]:   File "/home/jibri/jibri-xmpp-client/app.py", line 521, in jibri_start_callback
Nov 02 13:24:27 jibri app.py[3473]:     jibri_stop_callback('startup_selenium_error')
Nov 02 13:24:27 jibri app.py[3473]:   File "/home/jibri/jibri-xmpp-client/app.py", line 794, in jibri_stop_callback
Nov 02 13:24:27 jibri app.py[3473]:     finalize_recording()
Nov 02 13:24:27 jibri app.py[3473]:   File "/home/jibri/jibri-xmpp-client/app.py", line 203, in finalize_recording
Nov 02 13:24:27 jibri app.py[3473]:     call([finalize_recording_script,recording_directory])
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/subprocess.py", line 557, in call
Nov 02 13:24:27 jibri app.py[3473]:     with Popen(*popenargs, **kwargs) as p:
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
Nov 02 13:24:27 jibri app.py[3473]:     restore_signals, start_new_session)
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
Nov 02 13:24:27 jibri app.py[3473]:     raise child_exception_type(errno_num, err_msg)
Nov 02 13:24:27 jibri app.py[3473]: PermissionError: [Errno 13] Permission denied
Nov 02 13:47:37 jibri app.py[3473]: 2017-11-02 13:47:37,867 ERROR    Socket Error #104: Connection reset by peer
Nov 02 13:47:37 jibri app.py[3473]: 2017-11-02 13:47:37,868 WARNING  Failed to send b'</stream:stream>'
Nov 02 13:47:37 jibri app.py[3473]: 2017-11-02 13:47:37,869 INFO     Waiting for </stream:stream> from server
Nov 02 13:47:44 jibri app.py[3473]: 2017-11-02 13:47:44,475 INFO     Negotiating TLS
Nov 02 13:47:44 jibri app.py[3473]: 2017-11-02 13:47:44,476 INFO     Using SSL version: TLS 1.0
Nov 02 13:47:44 jibri app.py[3473]: 2017-11-02 13:47:44,836 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,349 INFO     JID set to: jibri@auth.my.domain.com/e7d2b396-627a-4a7c-88f3-3bebf2a08ea5
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,407 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,408 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>, connecting to room TheBrewery@conference.my.domain.com as jibri-41832950736615837
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,480 INFO     sending presence: <presence xml:lang="en" to="TheBrewery@conference.my.domain.com"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="idle" /></presence>
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,482 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>
```

I know there's troubleshooting in readme, but I don't understand.
Can you guide me?
Thank you

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian repository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
