### ISSUE TITLE
Unexpected status received in response to the start IQ:

### ISSUE THREAD

**Issue by zakirIndia** [jitsi/jibri#534]
```
Jicofo 2024-01-09 08:12:03.671 INFO: [52] [room=xyz@conference.meet.billingprobe.com meeting_id=e92273b5-a006-495d-866b-7bf067912b17] BaseJibri.handleJibriRequest#75: Accepted jibri request: <iq xmlns='jabber:client' to='focus@auth.meet.billingprobe.com/focus' from='xyz@conference.meet.billingprobe.com/7df81a06' id='Zm9jdXNAYXV0aC5tZWV0LmJpbGxpbmdwcm9iZS5jb20vZm9jdXMAMTQ5NmI1NWEtYTkyZS00YTQ5LWJmNmEtNjU1ZTJmNGQzM2I4OnNlbmRJUQBN28qISn58XA==' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='file' app_data='{"file_recording_metadata":{"share":false}}'/></iq>
Jicofo 2024-01-09 08:12:03.672 INFO: [53] [room=xyz@conference.meet.billingprobe.com meeting_id=e92273b5-a006-495d-866b-7bf067912b17] JibriSession.startInternal#317: Starting session with Jibri jibribrewery@internal.auth.meet.billingprobe.com/jibri
Jicofo 2024-01-09 08:12:03.672 INFO: [53] [room=xyz@conference.meet.billingprobe.com meeting_id=e92273b5-a006-495d-866b-7bf067912b17] JibriSession.sendJibriStartIq#471: Starting Jibri jibribrewery@internal.auth.meet.billingprobe.com/jibri for stream ID: null in room: xyz@conference.meet.billingprobe.com
Jicofo 2024-01-09 08:12:04.051 SEVERE: [53] [room=xyz@conference.meet.billingprobe.com meeting_id=e92273b5-a006-495d-866b-7bf067912b17] JibriSession.sendJibriStartIq#552: Unexpected status received in response to the start IQ: <iq xmlns='jabber:client' to='focus@auth.meet.billingprobe.com/focus' from='jibribrewery@internal.auth.meet.billingprobe.com/jibri' id='8Q8MC-319' type='result'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
Jicofo 2024-01-09 08:12:04.052 SEVERE: [53] [room=xyz@conference.meet.billingprobe.com meeting_id=e92273b5-a006-495d-866b-7bf067912b17] JibriSession.startInternal#323: Failed to send start Jibri IQ: org.jitsi.jicofo.jibri.JibriSession$StartException$UnexpectedResponse: Unexpected response
org.jitsi.jicofo.jibri.JibriSession$StartException$UnexpectedResponse: Unexpected response
        at org.jitsi.jicofo.jibri.JibriSession.sendJibriStartIq(JibriSession.java:555)
        at org.jitsi.jicofo.jibri.JibriSession.startInternal(JibriSession.java:319)
        at org.jitsi.jicofo.jibri.JibriSession.start(JibriSession.java:283)
        at org.jitsi.jicofo.jibri.JibriRecorder.handleStartRequest(JibriRecorder.kt:117)
        at org.jitsi.jicofo.jibri.BaseJibri.doHandleIQRequest(BaseJibri.kt:166)
        at org.jitsi.jicofo.jibri.BaseJibri.incomingIqQueue$lambda$0(BaseJibri.kt:57)
        at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
        at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:137)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2024-01-09 08:12:04.052 INFO: [53] JibriDetector.instanceFailed#90: Instance failed: jibribrewery@internal.auth.meet.billingprobe.com/jibri. Will not be selected for the next PT1M
Jicofo 2024-01-09 08:12:04.052 SEVERE: [53] [room=xyz@conference.meet.billingprobe.com meeting_id=e92273b5-a006-495d-866b-7bf067912b17] JibriSession.startInternal#305: Unable to find an available Jibri, can't start
Jicofo 2024-01-09 08:12:04.052 INFO: [53] [room=xyz@conference.meet.billingprobe.com meeting_id=e92273b5-a006-495d-866b-7bf067912b17] JibriRecorder.handleStartRequest#124: Failed to start a Jibri session, all Jibris were busy
```

**Comment by zakirIndia** [comment]
log.0.txt

```
2024-01-09 08:25:35.007 INFO: [84] XmppApi.handleJibriIq#239: Received JibriIq <iq xmlns='jabber:client' to='jibri@auth.meet.billingprobe.com/e3IWULcMRIXe' from='jibribrewery@internal.auth.meet.billingprobe.com/focus' id='amlicmlAYXV0aC5tZWV0LmJpbGxpbmdwcm9iZS5jb20vZTNJV1VMY01SSVhlADhROE1DLTQ4NQAZ5Zwp+sEaEA==' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='file' room='xyz@conference.meet.billingprobe.com' session_id='fkzuvkoqasjfabiw' app_data='{"file_recording_metadata":{"share":true}}'/></iq> from environment [MucClient id=meet.billingprobe.com hostname=meet.billingprobe.com]
2024-01-09 08:25:35.008 INFO: [84] XmppApi.handleStartJibriIq#271: Received start request, starting service
2024-01-09 08:25:35.012 INFO: [84] XmppApi.handleStartService#382: Parsed call url info: CallUrlInfo(baseUrl=https://meet.billingprobe.com, callName=xyz, urlParams=[])
2024-01-09 08:25:35.013 INFO: [84] JibriManager.startFileRecording#152: Starting a file recording with params: FileRecordingRequestParams(callParams=CallParams(callUrlInfo=CallUrlInfo(baseUrl=https://meet.billingprobe.com, callName=xyz, urlParams=[]), email='', passcode=null, callStatsUsernameOverride=, displayName=), sessionId=fkzuvkoqasjfabiw, callLoginParams=XmppCredentials(domain=recorder.meet.billingprobe.com, port=null, username=recorder, password=*****))
2024-01-09 08:25:35.014 FINE: [84] [session_id=fkzuvkoqasjfabiw] FfmpegCapturer.<init>#92: Detected os as OS: LINUX
2024-01-09 08:25:35.431 SEVERE: [84] XmppApi.handleStartJibriIq#303: Error starting Jibri service
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 120.0.6099.199 with binary path /usr/bin/google-chrome
  (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Linux 5.4.0-169-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 372 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'meet.billingprobe.com', ip: '172.105.57.144', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-169-generic', java.version: '11.0.21'
Driver info: driver.version: ChromeDriver
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
        at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:199)
        at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:167)
        at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:109)
        at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:96)
        at org.jitsi.jibri.JibriManager.startFileRecording(JibriManager.kt:153)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:386)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq(XmppApi.kt:278)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq(XmppApi.kt:246)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleIq(XmppApi.kt:228)
        at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:551)
        at org.jitsi.xmpp.mucclient.MucClient$3.handleIQRequest(MucClient.java:514)
        at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1561)
        at org.jivesoftware.smack.AbstractXMPPConnection$10.run(AbstractXMPPConnection.java:2146)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by saghul** [comment]
> This version of ChromeDriver only supports Chrome version 114
Current browser version is 120.0.6099.199 with binary path /usr/bin/google-chrome

You need to install a version of chromedriver that is compatible with the version of google chrome you installed.
