### ISSUE TITLE
Jibri not working (selenium.common.exceptions.WebDriverException)

### ISSUE THREAD

**Issue by pekubu** [jitsi/jibri#74]
```
root@ip-10-0-1-204:/home/jibri/jibri-xmpp-client# DISPLAY=:0 ./jibriselenium.py -u https://calling-jitsi-jicofo-dev.calling.fun/123
Initializing Driver
2018-03-15 02:37:05,821 DEBUG    POST http://127.0.0.1:55722/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"platformName": "any", "browserName": "chrome", "goog:chromeOptions": {"args": ["--use-fake-ui-for-media-stream", "--start-maximized", "--kiosk", "--enabled", "--enable-logging", "--vmodule=*=3", "--disable-infobars", "--alsa-output-device=plug:amix"], "extensions": []}}}, "desiredCapabilities": {"platform": "ANY", "goog:chromeOptions": {"args": ["--use-fake-ui-for-media-stream", "--start-maximized", "--kiosk", "--enabled", "--enable-logging", "--vmodule=*=3", "--disable-infobars", "--alsa-output-device=plug:amix"], "extensions": []}, "version": "", "browserName": "chrome", "loggingPrefs": {"browser": "ALL"}}}

2018-03-15 02:38:05,872 DEBUG    Finished Request
Traceback (most recent call last):
  File "./jibriselenium.py", line 324, in <module>
    js = JibriSeleniumDriver(URL,token,displayname=displayname,email=email,pjsua_flag=pjsua_flag)
  File "./jibriselenium.py", line 69, in __init__
    self.initDriver()
  File "./jibriselenium.py", line 83, in initDriver
    self.driver = webdriver.Chrome(chrome_options=options, desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-116-generic x86_64)

```

And i check  jibri-xorg, It also does not work. How to fix it? Thank you.

```
root@ip-10-0-1-204:/home/jibri/jibri-xmpp-client# service jibri-xorg status
● jibri-xorg.service - Jibri Xorg Process
   Loaded: loaded (/etc/systemd/system/jibri-xorg.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: jibri-xorg.service: Service hold-off time over, scheduling restart.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: Stopped Jibri Xorg Process.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: Started Jibri Xorg Process.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: jibri-xorg.service: Main process exited, code=exited, status=217/USER
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: jibri-xorg.service: Unit entered failed state.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: jibri-xorg.service: Failed with result 'exit-code'.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: jibri-xorg.service: Service hold-off time over, scheduling restart.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: Stopped Jibri Xorg Process.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: jibri-xorg.service: Start request repeated too quickly.
Mar 15 02:36:56 ip-10-0-1-204 systemd[1]: Failed to start Jibri Xorg Process.

```

**Comment by fuqiangleon** [comment]
i have some python error  ,but my jibri  is installed in a ubuntu docker container,have you tried to start jibri-xorg service with command?
